# Generated by Django 5.0.2 on 2024-02-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nomeProdutorRural', models.CharField(max_length=100, verbose_name='Nome do Produtor Rural')),
                ('cpfcnpj', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
            ],
            options={
                'verbose_name': 'ProdutorRural',
                'verbose_name_plural': 'ProdudoresRurais',
            },
        ),
        migrations.CreateModel(
            name='TipoCultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tipoCultura', models.CharField(max_length=50, verbose_name='Tipo de Cultura')),
            ],
            options={
                'verbose_name': 'TipoCultura',
                'verbose_name_plural': 'TiposCultura',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nomeFazenda', models.CharField(max_length=100, verbose_name='Nome da Fazenda')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('ac', 'AC'), ('am', 'AM'), ('ro', 'RO'), ('rr', 'PA'), ('ap', 'AP'), ('to', 'TO'), ('ma', 'MA'), ('pi', 'PI'), ('ce', 'CE'), ('rn', 'RN'), ('pb', 'PB'), ('pe', 'PE'), ('al', 'AL'), ('se', 'SE'), ('ba', 'BA'), ('mg', 'MG'), ('es', 'ES'), ('rj', 'RJ'), ('sp', 'SP'), ('pr', 'PR'), ('sc', 'SC'), ('rs', 'RS'), ('ms', 'MS'), ('mt', 'MT'), ('go', 'GO'), ('df', 'DF')], max_length=2, verbose_name='Estado')),
                ('areaTotal', models.FloatField(blank=True, default=None, null=True)),
                ('areaAgricultavel', models.FloatField(blank=True, default=None, null=True)),
                ('areaVegetacao', models.FloatField(blank=True, default=None, null=True)),
                ('produtorRural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtorrural', verbose_name='ProdutorRural')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='FazendaCulturaPlantada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda', verbose_name='Fazenda')),
                ('tipoCultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocultura', verbose_name='TipoCultura')),
            ],
            options={
                'verbose_name': 'FazendaCulturaPlantada',
                'verbose_name_plural': 'FazendasCulturasPlantadas',
            },
        ),
    ]
